#setup_beegfs_mgmt_config.yml

#setup_beegfs_mgmt_config
#username of the host where you are trying to bring up the beegfs mgmt server
username: Amogha

#IP of the host where you are trying to bring up the beegfs mgmt server
ip: <ip>

#provide the beegfs version which you want to bring up on your mgmt server 
beegfs_version: <version>

#pervide the beegfs serverip
beegfs_server_ip: <beegfs_server_ip>